//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Exam_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAnswer
    {
        public int StudentAnswerID { get; set; }
        public Nullable<int> Studentid { get; set; }
        public Nullable<int> ExamID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public string SelectedOption { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual Question Question { get; set; }
        public virtual Student Student { get; set; }
    }
}
